apiVersion: v1
kind: Service
metadata:
  name: krgeobuk-mysql
spec:
  type: ExternalName
  externalName: 127.0.0.1
  ports:
    - name: mysql-auth
      port: 3307
      targetPort: 3307
    - name: mysql-authz
      port: 3308
      targetPort: 3308
    - name: mysql-portal
      port: 3309
      targetPort: 3309
    - name: mysql-mypick
      port: 3310
      targetPort: 3310
