apiVersion: v1
kind: Service
metadata:
  name: krgeobuk-redis-auth
spec:
  type: ExternalName
  externalName: 127.0.0.1
  ports:
    - name: redis
      port: 6380
      targetPort: 6380
---
apiVersion: v1
kind: Service
metadata:
  name: krgeobuk-redis-authz
spec:
  type: ExternalName
  externalName: 127.0.0.1
  ports:
    - name: redis
      port: 6381
      targetPort: 6381
