apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pick-server
spec:
  replicas: 1  # dev는 1개
  template:
    spec:
      containers:
      - name: my-pick-server
        resources:
          requests:
            cpu: 100m  # dev는 최소 리소스
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 384Mi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-pick-server-config
data:
  LOG_LEVEL: "debug"  # dev는 debug 레벨
  NODE_ENV: "development"
